In [1]:
import numpy as np

In [4]:
numbers = [1,2,3,4,5]
print(numbers)

[1, 2, 3, 4, 5]


In [6]:
# How to create an array in numpy

In [7]:
array = np.array(numbers)

In [8]:
print(array)

[1 2 3 4 5]


In [9]:
# multiply every element by 2 

In [11]:
double = array * 2
print(double)

[ 2  4  6  8 10]


In [13]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
ones = np.ones((3))
print(ones)

[1. 1. 1.]


In [16]:
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


In [18]:
# challenge 1 create an array from 0-9
array_num = np.arange(0,10)
print(array_num)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
# challenge 2 create a pyramid of ones
matrix_ones = np.ones((4,4))
print(matrix_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
# challenge 3 evenly space numbers between 0 and 1 using linspace
even_space = np.linspace(0, 1, 5)
print(even_space)

[0.   0.25 0.5  0.75 1.  ]


In [25]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("The whole matrix", mat)

The whole matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print("The element at row1, column 2 :", mat[0][1]) # can also write it as mat[0,1]

The element at row1, column 2 : 2


In [28]:
print("pick the second number from every row: ", mat[:,1])

pick the second number from every row:  [2 5 8]


In [29]:
print("pick every row and choose the third number", mat[:,2])

pick every row and choose the third number [3 6 9]


In [31]:
# create an array of numbers 1-10

In [32]:
array_num_2 = np.arange(1,11)
print(array_num_2)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
sliced_5 = array_num_2[:5]
print(sliced_5)

[1 2 3 4 5]


In [40]:
extracted_matrix = mat[:2,:] # extract the first 2 rows 
print(extracted_matrix)

[[1 2 3]
 [4 5 6]]


In [45]:
bottom_right_matrix = mat[1:,1:] # slicing from bottom 2nd number from right
print(bottom_right_matrix)

[[5 6]
 [8 9]]


In [46]:
array_6 = np.arange(12)
print(array_6)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [47]:
print("shape", array_6.shape)

shape (12,)


In [49]:
print("dimention", array_6.ndim)

dimention 1


In [50]:
print("size", array_6.size)

size 12


In [52]:
array_7 = np.arange(1,13)
print(array_7)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [53]:
# reshape this array 

In [54]:
# reshape(3,4) saying 3 rows with 4 items
reshaped = array_7.reshape(3,4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
# can also flatten a multi dimentional array 
flat = reshaped.ravel()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [57]:
reshaped_2 = array_7.reshape(4,3)
print(reshaped_2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [87]:
extract_middle_2 = reshaped_2[:, 1:3] # all rows from column 1 to column to column 3
print(extract_middle_2)

[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


In [89]:
flat_2 = extract_middle_2.flatten() #flatten column extracted 
print(flat_2)

[ 2  3  5  6  8  9 11 12]


In [90]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a)
print(b)


[1 2 3 4]
[10 20 30 40]


In [91]:
print("a+b", a + b)

a+b [11 22 33 44]


In [92]:
print("a-b", a - b)

a-b [ -9 -18 -27 -36]


In [93]:
print("a / b", a / b)

a / b [0.1 0.1 0.1 0.1]


In [96]:
# square root
print("square root", np.sqrt(a))
# exponential 
print("expo of b", np.exp(b))

square root [1.         1.41421356 1.73205081 2.        ]
expo of b [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]


In [99]:
array_8 = np.arange(5,20,5)
array_9 = np.arange(2,7,2)
print(array_8)
print(array_9)

[ 5 10 15]
[2 4 6]


In [100]:
print(array_8 + array_9)

[ 7 14 21]


In [101]:
print(array_8 - array_9)

[3 6 9]


In [102]:
print(array_8 * array_9)

[10 40 90]


In [103]:
print(array_8 / array_9)

[2.5 2.5 2.5]


In [105]:
cubed = np.power(array_8,3)
# or you can do 
cube = array_8 ** 3
print(cubed)
print(cube)

[ 125 1000 3375]
[ 125 1000 3375]


In [106]:
broad = np.array([1,2,3,4,5])
# add 10 to each element
print("array + 10 to each item", broad + 10) # when you say + 10 its streaching 10 across each item and creating [10,10,10,10] and adding to each element in array 


array + 10 to each item [11 12 13 14 15]


In [107]:
# multiply
print("array * 5", broad * 5)

array * 5 [ 5 10 15 20 25]


In [108]:
arr2d = np.array([[1,2,3],[4,5,6]])
print("our full 2d array", arr2d)

our full 2d array [[1 2 3]
 [4 5 6]]


In [109]:
# want to add an array 10,20,30 to my existing array
print("add the array [10,20,30]", np.array([10,20,30]) + arr2d)

add the array [10,20,30] [[11 22 33]
 [14 25 36]]


In [110]:
array_9 = np.array([2,4,6,8])
print(array_9)

[2 4 6 8]


In [111]:
print(array_9 * 0.5)

[1. 2. 3. 4.]


In [120]:
matrix_ones_2 = np.ones((3,3))
print(matrix_ones_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [126]:
print(matrix_ones_2 + np.array([1,2,3]))

[[2. 3. 4.]
 [2. 3. 4.]]


In [122]:
matrix_ones_2 = np.ones((2,3))
print(matrix_ones_2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [124]:
print(matrix_ones_2 + 10)

[[11. 11. 11.]
 [11. 11. 11.]]


In [127]:
# create matrix 
matrix_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_3x3 + np.array([1,2,3]))

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [129]:
#experimenting
print(np.ones((4,4)) + np.array([1,2,3,4]))

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


In [131]:
import time 

size = 1_000_000
#python list 
list_1 = list(range(size)) # creating the list 
start = time.time() # starting on timer time were starting from
#loop over the list and print the list out 
list_2 = [x * 2 for x in list_1] # multiply list by 2 
print("Python list time: " , time.time() - start) # gives the time on how long it took to creatre list 


Python list time:  0.1369156837463379


In [132]:
numpy_1 = np.arange(size) # setting list size
start_1 = time.time() # getting current time, starting timer
numpy_2 = numpy_1 * 2 # times the array by 2 
print("numpy array time :", time.time() - start_1)

# numpy is alot faster if you look at the time compared to python thats why its useful when handling large data 

numpy array time : 0.00440526008605957


In [133]:
# random method - stats functions 

In [134]:
# Random 
## random numbers generated from random that will be and example of a dice role
dice = np.random.randint(1,7, size=10) # low = 1 high = 7 and we want size of 10
print(dice)

[6 6 5 5 6 6 1 6 5 1]


In [135]:
## random floats 
rand_floats = np.random.rand(5)
print(rand_floats)

[0.09894851 0.63080387 0.88525376 0.67172595 0.48678753]


In [136]:
## random normal distribution 
rand_dist = np.random.randn(5)
print(rand_dist)

[-0.79697093  0.10815329 -0.17766932  0.28473174  0.32238873]


In [137]:
dice_roll_20 = np.random.randint(1,7, size=20)
print(dice_roll_20)

[5 2 1 2 4 4 2 3 2 5 2 1 2 3 3 5 6 3 2 5]


In [139]:
print(dice_roll_20.min())

1


In [140]:
print(dice_roll_20.max())

6


In [148]:
rand_floats_2 = np.random.uniform(0, 10, size=10)
print(rand_floats_2)

[2.15541757 3.4468007  9.49025446 1.09122594 9.3525102  2.42951723
 1.65995673 2.52528912 1.97675976 2.090296  ]


In [144]:
rand_dist_2 = np.random.randn(1000)
print(rand_dist_2)

[ 1.04373092e+00 -1.18862129e+00 -1.03953951e+00  3.55628326e-01
 -5.79951770e-01 -9.69963003e-02  1.41504077e+00 -7.71164577e-01
  6.72430643e-01  1.34982280e+00  6.39186064e-01 -6.53343066e-01
 -1.06306791e+00  2.83662860e-01 -1.63005387e-01 -1.19593551e+00
 -1.38634624e+00  1.27079664e+00 -1.21985544e-01  3.00027850e+00
  9.12733015e-01  9.20423382e-01 -6.15730653e-01  1.09543868e+00
 -1.63270940e-01 -8.01988146e-01  7.41322791e-01  8.65603089e-01
 -1.30160629e+00  1.08278493e+00  4.84054697e-01  5.24772363e-01
  9.80691473e-01 -3.51715061e-01  4.85334774e-02  1.86449964e-02
 -1.13569547e+00 -7.60947322e-01  3.02503920e-01 -1.94462946e+00
 -7.30354342e-01 -8.47678990e-01 -6.91837389e-01 -1.15413158e+00
 -1.33387912e+00  6.98967575e-01 -1.09142921e+00  1.72411243e-01
  9.36715153e-01 -1.75521891e-01 -2.37491183e+00 -7.79437992e-01
  1.37699758e+00 -1.43914082e+00 -1.50222467e-01 -1.64363925e+00
 -1.90324773e+00  1.36215086e+00  7.09240363e-01 -1.40515932e+00
  1.73502414e-01  2.34744

In [147]:
print(rand_dist_2[:10]) # prints out first 10


[ 1.04373092 -1.18862129 -1.03953951  0.35562833 -0.57995177 -0.0969963
  1.41504077 -0.77116458  0.67243064  1.3498228 ]


In [152]:
statsarray = np.array([1,2,3,4,5,6,7,8,9,10])
# sum 
print("sum: ", np.sum(statsarray))
# mean 
print("mean: ", np.mean(statsarray))
# median 
print("median: ", np.median(statsarray))
# standard deviation 
print("SD: ", np.std(statsarray))
# min 
print("min: ", np.min(statsarray))
# max
print("max: ", np.max(statsarray))

sum:  55
mean:  5.5
median:  5.5
SD:  2.8722813232690143
min:  1
max:  10


In [156]:
print(np.sum(dice_roll_20))
print(np.mean(dice_roll_20))
print(np.median(dice_roll_20))
print(np.std(dice_roll_20))

62
3.1
3.0
1.445683229480096


In [160]:
random_int = np.random.randint(10,101, size=50)
print(random_int)
print(np.mean(random_int))
print(np.median(random_int))
print(np.std(random_int))

[14 81 17 72 49 93 92 88 78 94 47 55 60 45 86 82 57 44 64 63 44 49 20 57
 89 70 13 19 84 49 56 32 90 73 61 51 19 53 15 12 68 61 71 60 56 62 72 80
 95 57]
58.38
60.0
23.788139902060436


In [163]:
stack_1 = np.array([1,2,3])
stack_2 = np.array([4,5,6])

print(stack_1)
print(stack_2)

[1 2 3]
[4 5 6]


In [167]:
vstacked = np.vstack([stack_1,stack_2])
print(vstacked)

[[1 2 3]
 [4 5 6]]


In [168]:
hstacked = np.hstack([stack_1,stack_2])
print(hstacked)

[1 2 3 4 5 6]


In [171]:
array_1d = np.random.randint(0,50,size=16)
array_reshape = array_1d.reshape(4,4)
print(array_1d)
print(array_reshape)

[22  0 15 19  7  8 34 16  3 34 34 20 26 16 41 19]
[[22  0 15 19]
 [ 7  8 34 16]
 [ 3 34 34 20]
 [26 16 41 19]]


In [172]:
sarray_1 = np.array([1,2])
sarray_2 = np.array([3,4])
vstackedarr = np.vstack([sarray_1,sarray_2])
hstackedarr = np.hstack([sarray_1,sarray_2])
print(vstackedarr)
print(hstackedarr)

[[1 2]
 [3 4]]
[1 2 3 4]


In [176]:
dice_3 = np.random.randint(1,7, size=5)
dice_4 = np.random.randint(1,7, size=5)
vstackeddice = np.vstack([dice_3,dice_4])
print(vstackeddice)

[[6 3 1 1 3]
 [3 4 6 4 1]]


In [175]:
print(np.vstack([dice_3,dice_4]))
# dice_reshape = hstackeddice.reshape(2,5)

[[5 1 2 5 1]
 [3 4 1 2 2]]
